# Generated by Django 5.1.2 on 2025-06-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_picture', models.ImageField(upload_to='Item_pictures/')),
                ('item_description', models.TextField()),
                ('contactEmail', models.EmailField(max_length=254)),
                ('found_at', models.CharField(max_length=100)),
                ('reported_datetime', models.DateTimeField(auto_now_add=True)),
                ('found_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('lost', 'lost'), ('found', 'found')], default='lost', max_length=5)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_items', to=settings.AUTH_USER_MODEL)),
                ('item_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
