# Generated by Django 5.1.2 on 2025-06-18 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userprofile_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='item_founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='main.userprofile'),
        ),
    ]
